background {
    monitor =
    path = ~/wallpapers/demon.mp4
    blur_passes = 3
    blur_size = 8
}

general {
    disable_loading_bar = true
    hide_cursor = false
}

input-field {
    monitor =
    size = 320, 55

    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.3

    dots_center = true

    outer_color = rgba(137,180,250,0.7)
    inner_color = rgba(17,17,27,0.4)

    font_color = rgb(205,214,244)

    fade_on_empty = false
    placeholder_text = <span foreground="##cdd6f4">󰌾  Password...</span>

    position = 0, -80
    halign = center
    valign = center

    rounding = 18
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"

    color = rgba(205,214,244,0.9)

    font_size = 90
    font_family = JetBrainsMono Nerd Font Mono ExtraBold

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"

    color = rgba(137,180,250,0.8)

    font_size = 22
    font_family = JetBrainsMono Nerd Font Mono

    position = 0, 40
    halign = center
    valign = center
}
